config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :index, :show]
  resource :session, only: [:new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  validates :username, :session_token, presence: true, uniqueness: true
  validates :favorite_drink, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  # SPIRE

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
    nil
  end

  def is_password?(password)
    bcrypt_thing = BCrypt::Password.new(self.password_digest) # makes a bcrypt object
    bcrypt_thing.is_password?(password) # checks to see if password gets digested right 
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password) # makes a digest
    @password = password
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64 # random string
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # LL CRL J

  helper_method :current_user, :logged_in?

  def login!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def logout!
    # current_user.reset_session_token! # you should have this
    session[:session_token] = nil
    # @current_user = nil
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_logged_in?
    redirect_to new_session_url unless logged_in?
  end
  
  def logged_in?
    !!current_user # double negative = NOT NOT current_user = true if user false if no user
  end

  def jay
    p "yo"
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if user
      login!(user)
      redirect_to user_url(user) # show page -> user_url(user) -> "users/22"
    else
      flash.now[:errors] = ["whatever error you want"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    # request coming in
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to users_url
      # response going out
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :favorite_drink, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MikeCircleAkaFutureRailsChampions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:errors] %>

    <% if logged_in? %>
      <%= current_user.username %>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Sign Out">
      </form>
    <% else %>
      <a href="<%= new_user_url %>">Sign Up</a>
      <a href="<%= new_session_url %>">Sign In</a>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>New User / Sign Up</h1>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username 
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  <label>Password 
    <input type="password" placeholder="password" name="user[password]" value="">
  </label>
  <label>Fav Drink
    <input type="text" name="user[favorite_drink]" value="<%= @user.favorite_drink%>">
  </label>

  <input type="submit" value="Create User!">


</form>